services:



    creative_selectel.config.config:
        class: Creative\SelectelBundle\Config\MemoryConfig
        arguments:
            $accountId: '%creative_selectel.account_id%'
            $userId: '%creative_selectel.client_id%'
            $userPassword: '%creative_selectel.client_password%'
            $container: '%creative_selectel.container%'
            $apiHost: '%creative_selectel.api_host%'

    Creative\SelectelBundle\Config\ConfigInterface:
        alias: '@creative_selectel.config.config'



    creative_selectel.service.transport:
        class: GuzzleHttp\Client



    creative_selectel.service.service:
        class: Creative\SelectelBundle\Service\SelectelService
        arguments:
            $config: '@creative_selectel.config.config'
            $transport: '@creative_selectel.service.transport'

    Creative\SelectelBundle\Service\ServiceInterface:
        alias: creative_selectel.service.service



    creative_selectel.adapter.adapter:
        class: Creative\SelectelBundle\Adapter\SelectelAdapter
        arguments:
            $service: '@creative_selectel.service.service'

    Creative\SelectelBundle\Adapter\SelectelAdapter:
        alias: creative_selectel.adapter.adapter
